<!DOCTYPE html>
<html lang="en">
<head>
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title>NgakakSeru- Santai Aja Kali</title> 
	<meta name="description" content="Ngakak Seru Website Lucu"/>
	<meta name="keywords" content="fun,funny,lol,meme,GIF,wtf,omg,fail,video,cosplay,geeky,forever alone" />
	<meta name="author" content="DDA Academy"/>
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: Facebook Open Graph -->
	<meta property="og:title" content=""/>
	<meta property="og:description" content=""/>
	<meta property="og:type" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:image" content=""/>
	<!-- end: Facebook Open Graph -->

    <!-- start: CSS -->
    <link href="../main/css/bootstrap.css" rel="stylesheet">
    <link href="../main/css/bootstrap-responsive.css" rel="stylesheet">
	<link href="../main/css/style.css" rel="stylesheet">
    <link href="../main/css/custom.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Serif">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Boogaloo">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Economica:700,400italic">
	<link href="../main/img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
	<!-- end: CSS -->

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>
	
	<!--start: Header -->
	<header>	
	<!DOCTYPE HTML>
		<!--start: Container -->
		<div class="container">
			
			<!--start: Row -->
			<div class="row">
					
				<!--start: Logo -->
				<div class="logo span3">
						
					<a class="brand" href="#"><img src="../main/img/logo.png"></a>
						
				</div>
				<!--end: Logo -->
					
				<!--start: Navigation -->
				<div class="span9">
						
					<div class="navbar navbar-inverse">
			    		<div class="navbar-inner">
			        		<div class="container">
			          			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			            			<span class="icon-bar"></span>
			            			<span class="icon-bar"></span>
			            			<span class="icon-bar"></span>
			          			</a>
			          			<div class="nav-collapse collapse">
			            			<ul class="nav">
			              				<li><a href="index.html">TOP</a></li>
			              				<li><a href="about.html">Trending</a></li>
										<li><a href="services.html">Terbaru</a></li>
										<li><a href="pricing.html">TV</a></li>
			              				<li class="dropdown">
			                				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Kategori <b class="caret"></b></a>
			                				<ul class="dropdown-menu">
			                  					<li><a href="#">Cewe</a></li>
			                  					<li><a href="#">NSWF</a></li>
			                  					<li><a href="#">GIF</a></li>
			                  					<li><a href="#">Meme</a></li>
			                  					<li><a href="#">Imut</a></li>
			                  					<li><a href="#">Cosplay</a></li>
			                  					<li><a href="#">Timely</a></li>
			                  					<li><a href="#">Komik</a></li>
			                  					<li><a href="#">Makanan</a></li>
			                				</ul>
			              				</li>
			            			</ul>
			          			</div>
			        		</div>
			      		</div>
			    	</div>
					
				</div>	
				<!--end: Navigation -->
                
			</div>
			<!--end: Row -->
			
		</div>
		<!--end: Container-->			
	</header>
	<!--end: Header-->

	<!-- start: Wrapper -->	
	<div id="wrapper">		

		<!-- start: Container -->	
		<div class="container">
			
			<!-- start: Row -->
			<div class="row">
                <div class="span8 main-container">
                    <div class="main">
            <br />
            <br />
            <br />
            <br />
        <div class="header" >
            <h1>Silahkan Login atau membuat akun GRATIS!</h1>
        </div>
        <p>Sebelum anda post konten, anda harus login terlebih dahulu. </p>
            <form action="<?=$base_url?>index.php/auth/login" method="POST">
                <ul class="right-form">
                    <h3>Login:</h3>
                    <div>
                        <li><input type="text"  placeholder="Username" name="username" required/></li>
                        <li> <input type="password"  placeholder="Password" name="password" required/></li>
                        <h4><a href="#">I forgot my Password!</a></h4>
                            <input type="submit" onclick="myFunction()" value="Login" >
                    </div>
                    <div class="clear"> </div>
                </ul>
            </form>
            <form action="<?=$base_url?>index.php/auth/register" method="POST">
                <br />
                <br />
                <ul class="left-form">
                    <h2>Buat Akun Baru:</h2>
                    <li>
                        <input type="text"   placeholder="Username" name="username" required/>
                        <a href="#" class="icon ticker"> </a>
                        <div class="clear"> </div>
                    </li> 
                    <li>
                        <input type="text"   placeholder="Email" name="email" required/>
                        <a href="#" class="icon ticker"> </a>
                        <div class="clear"> </div>
                    </li> 
                    <li>
                        <input type="password"   placeholder="password" name="password" required/>
                        <a href="#" class="icon into"> </a>
                        <div class="clear"> </div>
                    </li> 
                    <li>
                        <input type="password"   placeholder="password"  name="password_confirm" required/>
                        <a href="#" class="icon into"> </a>
                        <div class="clear"> </div>
                    </li> 
                    <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i>Saya setuju atas <a href="#">syarat</a> dan <a href="#">ketentuan</a> dari NgakakSeruCom</label>
                    <input type="submit" onclick="myFunction()" value="Create Account">
                        <div class="clear"> </div>
                </ul>
                
                <div class="clear"> </div>
                    
            </form>
            
        </div>
                </div>
                
                <div class="span4">
                    <div class="img-container-ads">
                        <img src="../main/img/bg-grey.png">
                    </div>
                    <div class="img-container-ads">
                        <img src="../main/img/bg-grey.png">
                    </div>
                    <div class="img-container-ads">
                        <img src="../main/img/bg-grey.png">
                    </div>
                    <h2>Subscribe</h2>
                        <input type="text" name="subcribe" class="form-control">
                        <button class="btn btn-default btn-md">Subscribe</button>
                        <br><br>
                    <h2>Get The App</h2>
                        <button class="btn btn-default">DOWNLOAD</button>
                        <br><br>
                    <div id="footer">
                        <a href="">Pasang Iklan</a> · <a href="">Kontak</a> · <a href="">Privasi</a> · <a href="">Peraturan</a>
                        <br>
                        www.NgakakSeru.com © 2014</a>
                    </div>
                </div>
			</div>
			<!-- end: Row -->

		</div>
		<!-- end: Container -->
				
  	</div>
	<!-- end: Wrapper  -->			
	</div>
    <!-- start: Footer Menu -->
	

	

<!-- start: Java Script -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../main/js/jquery-1.8.2.js"></script>
<script src="../main/js/bootstrap.js"></script>
<script src="../main/js/flexslider.js"></script>
<script src="../main/js/carousel.js"></script>
<script src="../main/js/jquery.cslider.js"></script>
<script src="../main/js/slider.js"></script>
<script def src="../main/js/custom.js"></script>
<!-- end: Java Script -->

</body>
</html>
