<?php $this->start('header') ?>
<header>
    <!--start: Container -->
    <div class="container">
        <!-- start: Row -->
        <div class="row">
            <!--start: Logo -->
            <div class="logo span3">

                <a class="brand" href="#"><img src="<?= $baseUrl; ?>/img/logo.png"></a>

            </div>
            <!--end: Logo -->

            <!--start: Navigation -->
            <div class="span9">

                <div class="navbar navbar-inverse">
                    <div class="navbar-inner">
                        <div class="container">
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>
                            <div class="nav-collapse collapse">
                                <ul class="nav">
                                    <li><a href="index.html">TOP</a></li>
                                    <li><a href="about.html">Trending</a></li>
                                    <li><a href="services.html">Terbaru</a></li>
                                    <li><a href="pricing.html">TV</a></li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kategori <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#">Cewe</a></li>
                                            <li><a href="#">NSWF</a></li>
                                            <li><a href="#">GIF</a></li>
                                            <li><a href="#">Meme</a></li>
                                            <li><a href="#">Imut</a></li>
                                            <li><a href="#">Cosplay</a></li>
                                            <li><a href="#">Timely</a></li>
                                            <li><a href="#">Komik</a></li>
                                            <li><a href="#">Makanan</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>	
            <!--end: Navigation -->
        </div>
        <!-- end: Row -->
    </div>
</header>
<?php $this->stop() ?>