<?php
//echo $config['site']['site_title'];
echo $config['url']['base_url_asset'];
?>
<?php $this->start('about') ?>
<!--<div class="span8 main-container">
    <div class="content-container">
        <div class="post-container">
            <h2>Judul Konten</h2><br>
            <div class="img-container">
                <img src="<?=$config['url']['base_url_asset'];?>/img/default-image.png">
            </div>
        </div>
        <div class="post-tool">
            <ul class="social-bookmarks ">
                <li class="facebook" title="Share"><a href="#">facebook</a></li>
                <li class="twitter" title="Tweet"><a href="#">twitter</a></li>
            </ul>
            <a href="" class="like" title="Suka"><i class="ico-thumbs-up  ico-white circle-color-full small-color"></i></a>
            <a href="" class="like" title="Tidak Suka"><i class="ico-thumbs-down  ico-white circle-color-full small-color"></i></a>
            <a href="" class="like" title="Komentar"><i class="ico-chat ico-white circle-color-full small-color"></i></a>
        </div>
    </div>
    <div class="content-container">
        <div class="post-container">
            <h2>Judul Konten</h2><br>
            <div class="img-container">
                <img src="../img/default-image.png">
            </div>
        </div>
        <div class="post-tool">
            <ul class="social-bookmarks ">
                <li class="facebook" title="Share"><a href="#">facebook</a></li>
                <li class="twitter" title="Tweet"><a href="#">twitter</a></li>
            </ul>
            <a href="" class="like" title="Suka"><i class="ico-thumbs-up  ico-white circle-color-full small-color"></i></a>
            <a href="" class="like" title="Tidak Suka"><i class="ico-thumbs-down  ico-white circle-color-full small-color"></i></a>
            <a href="" class="like" title="Komentar"><i class="ico-chat ico-white circle-color-full small-color"></i></a>
        </div>
    </div>
    <div class="content-container">
        <div class="post-container">
            <h2>Judul Konten</h2><br>
            <div class="img-container">
                <img src="../img/default-image.png">
            </div>
        </div>
        <div class="post-tool">
            <ul class="social-bookmarks ">
                <li class="facebook" title="Share"><a href="#">facebook</a></li>
                <li class="twitter" title="Tweet"><a href="#">twitter</a></li>
            </ul>
            <a href="" class="like" title="Suka"><i class="ico-thumbs-up  ico-white circle-color-full small-color"></i></a>
            <a href="" class="like" title="Tidak Suka"><i class="ico-thumbs-down  ico-white circle-color-full small-color"></i></a>
            <a href="" class="like" title="Komentar"><i class="ico-chat ico-white circle-color-full small-color"></i></a>
        </div>
    </div>
</div>-->