<?php $this->layout('template', $detail) ?>

<?php $this->start('home') ?>
<!-- start: Wrapper -->	
<div id="wrapper">		

    <!-- start: Container -->	
    <div class="container">

        <!-- start: Row -->
        <div class="row">
            <div class="span8 main-container">
                <div class="content-container">
                    <div class="post-container">
                        <h2>Judul Konten</h2><br>
                        <div class="img-container">
                            <img src="<?= $detail['baseUrl']; ?>/img/default-image.png">
                        </div>
                    </div>
                    <div class="post-tool">
                        <ul class="social-bookmarks ">
                            <li class="facebook" title="Share"><a href="#">facebook</a></li>
                            <li class="twitter" title="Tweet"><a href="#">twitter</a></li>
                        </ul>
                        <a href="" class="like" title="Suka"><i class="ico-thumbs-up  ico-white circle-color-full small-color"></i></a>
                        <a href="" class="like" title="Tidak Suka"><i class="ico-thumbs-down  ico-white circle-color-full small-color"></i></a>
                        <a href="" class="like" title="Komentar"><i class="ico-chat ico-white circle-color-full small-color"></i></a>
                    </div>
                </div>
                <div class="content-container">
                    <div class="post-container">
                        <h2>Judul Konten</h2><br>
                        <div class="img-container">
                            <img src="<?= $detail['baseUrl']; ?>/img/default-image.png">
                        </div>
                    </div>
                    <div class="post-tool">
                        <ul class="social-bookmarks ">
                            <li class="facebook" title="Share"><a href="#">facebook</a></li>
                            <li class="twitter" title="Tweet"><a href="#">twitter</a></li>
                        </ul>
                        <a href="" class="like" title="Suka"><i class="ico-thumbs-up  ico-white circle-color-full small-color"></i></a>
                        <a href="" class="like" title="Tidak Suka"><i class="ico-thumbs-down  ico-white circle-color-full small-color"></i></a>
                        <a href="" class="like" title="Komentar"><i class="ico-chat ico-white circle-color-full small-color"></i></a>
                    </div>
                </div>
                <div class="content-container">
                    <div class="post-container">
                        <h2>Judul Konten</h2><br>
                        <div class="img-container">
                            <img src="<?= $detail['baseUrl']; ?>/img/default-image.png">
                        </div>
                    </div>
                    <div class="post-tool">
                        <ul class="social-bookmarks ">
                            <li class="facebook" title="Share"><a href="#">facebook</a></li>
                            <li class="twitter" title="Tweet"><a href="#">twitter</a></li>
                        </ul>
                        <a href="" class="like" title="Suka"><i class="ico-thumbs-up  ico-white circle-color-full small-color"></i></a>
                        <a href="" class="like" title="Tidak Suka"><i class="ico-thumbs-down  ico-white circle-color-full small-color"></i></a>
                        <a href="" class="like" title="Komentar"><i class="ico-chat ico-white circle-color-full small-color"></i></a>
                    </div>
                </div>
            </div>
            <div class="span4">
                <div class="img-container-ads">
                    <img src="<?= $detail['baseUrl']; ?>/img/bg-grey.png">
                </div>
                <div class="img-container-ads">
                    <img src="<?= $detail['baseUrl']; ?>/img/bg-grey.png">
                </div>
                <div class="img-container-ads">
                    <img src="<?= $detail['baseUrl']; ?>/img/bg-grey.png">
                </div>
                <h2>Subscribe</h2>
                <input type="text" name="subcribe" class="form-control">
                <button class="btn btn-default btn-md">Subscribe</button>
                <br><br>
                <h2>Get The App</h2>
                <button class="btn btn-default">DOWNLOAD</button>
                <br><br>
                <div id="footer">
                    <a href="">Pasang Iklan</a> · <a href="">Kontak</a> · <a href="">Privasi</a> · <a href="">Peraturan</a>
                    <br>
                    www.NgakakSeru.com © 2014</a>
                </div>
            </div>

        </div>
        <!-- end: Row -->

    </div>
    <!-- end: Container -->

</div>
<!-- end: Wrapper  -->
<?php $this->stop() ?>
