<!doctype html>
<html>
<head>
    <title>
        <?php if ($this->section('title')) {
            echo $this->section('title');
        } ?>
    </title>
    <style>
        body {
            font-family: arial, helvetica;
            font-size: 14px;
            color: #333;
            line-height: 1.5;
        }
    </style>
</head>
<body>

<div class="content">
<?= $this->section('content') ?>
</div>

</body>
</html>

